### ISSUE TITLE
Welcome message name not email

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#91]
![screenshot from 2019-02-06 12-31-37](https://user-images.githubusercontent.com/6759913/52338669-092b8580-29d9-11e9-8a5b-f740bca5fe7f.png)

**Comment by hmcclungiii** [comment]
The reason this was overlooked to begin with is because there is no first and last name in the mybb_users table during the import.  There are only the username, email fields.

While resolving this issue, I found a small problem during the import.  The wrong person is being referenced by the forum_user.  The person_id_id field is being written with the user_id value, when they should be different.

When displaying the name, first see if there is a first/last name in the www_person table, if not then use the username.

The final step in resolving this issue was to make the new icon not be displayed in the threads when the user is not logged in.  After all, we can't mark them read or anything else if the user isn't logged in.

resolved in commit 171f1d83ecfd3b57a4fdf7291228f50e64f6fa44

![screenshot 89](https://user-images.githubusercontent.com/6778244/52497899-4d6b8100-2ba5-11e9-9405-d6b1f045b0a5.png)
![screenshot 90](https://user-images.githubusercontent.com/6778244/52497900-4d6b8100-2ba5-11e9-87cc-ab55884db158.png)
