### ISSUE TITLE
My profile page functionality

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/django#92]
There seems to be no normal way to go back from here: https://beta.openpsych.net/myprofile

**Comment by Deleetdk** [comment]
Also, the header shouldn't be "OpenPsych" in the profile page, it should be something sensible, like "User settings" or some such.

There is also no way to change password for users.

**Comment by hmcclungiii** [comment]
commit 7977e542d37738c92aa0b514c86cfb77b5b5f309 closes #92

Because of the way Users, Persons and ForumUsers are setup, I created separate pages for updating Profile, User Account email and username and finally the Change Password page.  The change password page needs its title updated.  Everything else looks good and the server has been updated at [https://beta.openpsych.net.](https://beta.openpsych.net.)

Showing what the message looks like when a successful update has been made.  In the future I'm going to make these messages a little more user friendly.
![edit_profile_success](https://user-images.githubusercontent.com/6778244/52999109-efd00380-33f2-11e9-885a-410cdb2df71f.png)
The Edit Profile page:
![edit_profile](https://user-images.githubusercontent.com/6778244/52999110-efd00380-33f2-11e9-99ca-025d6c235829.png)
The My Account page:
![my_account](https://user-images.githubusercontent.com/6778244/52999111-f0689a00-33f2-11e9-868c-636a9decf4d9.png)
The Change Password page:
![change_password](https://user-images.githubusercontent.com/6778244/52999112-f1013080-33f2-11e9-883c-2f16798a9576.png)
